# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1Api")

api.instance <- V1Api$new()

test_that("MatrixLambdasApiV1CoreGetFeatureDetail", {
  # tests for MatrixLambdasApiV1CoreGetFeatureDetail
  # base path: https://$
  # Get a information about a matrix feature type
  # @param character  feature.name  Feature type to describe 
  # @return [V1MatrixFeatureDetail]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CoreGetFeatures", {
  # tests for MatrixLambdasApiV1CoreGetFeatures
  # base path: https://$
  # Get a list of available feature types
  # Get a list of matrix feature types that a POST to /matrix will accept. 
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CoreGetFieldDetail", {
  # tests for MatrixLambdasApiV1CoreGetFieldDetail
  # base path: https://$
  # Get a description of a metadata field
  # Get detailed information about an available metadata field. 
  # @param character  field.name  Field to describe. 
  # @return [OneOfv1NumericFieldDetailv1CategoricalFieldDetail]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CoreGetFields", {
  # tests for MatrixLambdasApiV1CoreGetFields
  # base path: https://$
  # Get a list of available metadata fields
  # Get a list of metadata field names that a POST to /matrix will accept. 
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CoreGetFilterDetail", {
  # tests for MatrixLambdasApiV1CoreGetFilterDetail
  # base path: https://$
  # Get a description of a filter
  # Get detailed information about a filter that can be applied to the HCA expression data. 
  # @param character  filter.name  Filter to describe. 
  # @return [OneOfv1NumericFieldDetailv1CategoricalFieldDetail]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CoreGetFilters", {
  # tests for MatrixLambdasApiV1CoreGetFilters
  # base path: https://$
  # Get a list of permitted filters
  # Get a list of filters that a POST to /matrix will accept. 
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CoreGetFormatDetail", {
  # tests for MatrixLambdasApiV1CoreGetFormatDetail
  # base path: https://$
  # Get a description of a matrix format
  # @param character  format.name  Format to describe 
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CoreGetFormats", {
  # tests for MatrixLambdasApiV1CoreGetFormats
  # base path: https://$
  # Get a list of available matrix formats
  # Get a list of matrix formats that a POST to /matrix will accept. 
  # @return [array[character]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CoreGetMatrix", {
  # tests for MatrixLambdasApiV1CoreGetMatrix
  # base path: https://$
  # Get status and result of a matrix request
  # @param character  request.id  ID returned by a previous matrix request. 
  # @return [V1MatrixGetResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV1CorePostMatrix", {
  # tests for MatrixLambdasApiV1CorePostMatrix
  # base path: https://$
  # Request an expression matrix
  # Request an expression matrix using a set of filters to be ANDed and applied to the HCA expression data. 
  # @param V1MatrixRequest  v1.matrix.request    (optional)
  # @return [V1MatrixPostResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

