# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V0MatrixRequest")

model.instance <- V0MatrixRequest$new()

test_that("bundle_fqids", {
  # tests for the property `bundle_fqids` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`bundle_fqids`, "EXPECTED_RESULT")
})

test_that("bundle_fqids_url", {
  # tests for the property `bundle_fqids_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`bundle_fqids_url`, "EXPECTED_RESULT")
})

test_that("format", {
  # tests for the property `format` (V0MatrixFormat)

  # uncomment below to test the property 
  #expect_equal(model.instance$`format`, "EXPECTED_RESULT")
})

