# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1MatrixFeatureDetail")

model.instance <- V1MatrixFeatureDetail$new()

test_that("feature", {
  # tests for the property `feature` (character)
  # Feature type to include in the output matrix. For example, genes vs. transcripts. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`feature`, "EXPECTED_RESULT")
})

test_that("feature_description", {
  # tests for the property `feature_description` (character)
  # Description of the feature type.

  # uncomment below to test the property 
  #expect_equal(model.instance$`feature_description`, "EXPECTED_RESULT")
})

