# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1MatrixErrorResponse")

model.instance <- V1MatrixErrorResponse$new()

test_that("status_code", {
  # tests for the property `status_code` (integer)
  # HTTP status code of error.

  # uncomment below to test the property 
  #expect_equal(model.instance$`status_code`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)
  # Error message.

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

