# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1ComparisonFilterOperator")

model.instance <- V1ComparisonFilterOperator$new()

