# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1MatrixRequest")

model.instance <- V1MatrixRequest$new()

test_that("filter", {
  # tests for the property `filter` (V1MatrixFilter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`filter`, "EXPECTED_RESULT")
})

test_that("fields", {
  # tests for the property `fields` (array[character])
  # Metadata fields to include in output matrix.

  # uncomment below to test the property 
  #expect_equal(model.instance$`fields`, "EXPECTED_RESULT")
})

test_that("format", {
  # tests for the property `format` (character)
  # Format for the output matrix.

  # uncomment below to test the property 
  #expect_equal(model.instance$`format`, "EXPECTED_RESULT")
})

test_that("feature", {
  # tests for the property `feature` (character)
  # Feature type to include in the output matrix. For example, genes vs. transcripts. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`feature`, "EXPECTED_RESULT")
})

