# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1NumericFieldDetailAllOf")

model.instance <- V1NumericFieldDetailAllOf$new()

test_that("minimum", {
  # tests for the property `minimum` (numeric)
  # Minimum value for this field in the HCA expression data. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`minimum`, "EXPECTED_RESULT")
})

test_that("maximum", {
  # tests for the property `maximum` (numeric)
  # Maximum value for this field in the HCA expression data. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`maximum`, "EXPECTED_RESULT")
})

