# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V0MatrixPostResponse")

model.instance <- V0MatrixPostResponse$new()

test_that("request_id", {
  # tests for the property `request_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`request_id`, "EXPECTED_RESULT")
})

test_that("non_human_request_ids", {
  # tests for the property `non_human_request_ids` (map(character))

  # uncomment below to test the property 
  #expect_equal(model.instance$`non_human_request_ids`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (V0MatrixRequestStatus)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

