# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1MatrixGetResponse")

model.instance <- V1MatrixGetResponse$new()

test_that("request_id", {
  # tests for the property `request_id` (character)
  # UUID identifying a matrix request.

  # uncomment below to test the property 
  #expect_equal(model.instance$`request_id`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)
  # Status of a matrix request, for example whether it is still running or has finished. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("matrix_url", {
  # tests for the property `matrix_url` (character)
  # URL where matrix can be retrieved.

  # uncomment below to test the property 
  #expect_equal(model.instance$`matrix_url`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)
  # Additional information about the matrix request.

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("eta", {
  # tests for the property `eta` (character)
  # Estimated time remaining for the request to complete. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`eta`, "EXPECTED_RESULT")
})

