# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1ComparisonFilter")

model.instance <- V1ComparisonFilter$new()

test_that("op", {
  # tests for the property `op` (V1ComparisonFilterOperator)

  # uncomment below to test the property 
  #expect_equal(model.instance$`op`, "EXPECTED_RESULT")
})

test_that("field", {
  # tests for the property `field` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`field`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (OneOfstringnumberarray)

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

