# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1NumericFieldDetail")

model.instance <- V1NumericFieldDetail$new()

test_that("field_name", {
  # tests for the property `field_name` (character)
  # Name of the field.

  # uncomment below to test the property 
  #expect_equal(model.instance$`field_name`, "EXPECTED_RESULT")
})

test_that("field_description", {
  # tests for the property `field_description` (character)
  # Description of the meaning of the field.

  # uncomment below to test the property 
  #expect_equal(model.instance$`field_description`, "EXPECTED_RESULT")
})

test_that("field_type", {
  # tests for the property `field_type` (character)
  # Type of the field, for example numeric or categorical. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`field_type`, "EXPECTED_RESULT")
})

test_that("minimum", {
  # tests for the property `minimum` (numeric)
  # Minimum value for this field in the HCA expression data. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`minimum`, "EXPECTED_RESULT")
})

test_that("maximum", {
  # tests for the property `maximum` (numeric)
  # Maximum value for this field in the HCA expression data. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`maximum`, "EXPECTED_RESULT")
})

