# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V0Api")

api.instance <- V0Api$new()

test_that("MatrixLambdasApiV0CoreGetFormats", {
  # tests for MatrixLambdasApiV0CoreGetFormats
  # base path: https://$
  # Returns supported output formats.
  # Returns the list of expression matrix formats that can be requested from this service.
  # @return [array[V0MatrixFormat]]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV0CoreGetMatrix", {
  # tests for MatrixLambdasApiV0CoreGetMatrix
  # base path: https://$
  # Retrieve the status, and result if available, of a matrix query request.
  # Returns the status, and URI of the result if available, of a matrix query request. The status of a request can be &#39;Complete&#39;, &#39;In Progress&#39; or &#39;Failed&#39;. If the request is &#39;Complete&#39;, the matrix_location field will be populated with a URL to download the matrix. If the request &#39;Failed&#39;, the error message will be available in the message field.
  # @param character  request.id  The request ID generated by a POST request. 
  # @return [V0MatrixGetResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MatrixLambdasApiV0CorePostMatrix", {
  # tests for MatrixLambdasApiV0CorePostMatrix
  # base path: https://$
  # Submit a matrix query request.
  # Prepares a single expression matrix combining all expression matrices belonging to the specified analysis bundles. On success, this request will asynchronously start a job to prepare the expression matrix and return with the request ID of the job. The request ID can be used to retrieve the status and results of the job from the GET endpoint.
  # @param V0MatrixRequest  v0.matrix.request  Use either bundle_fqids or bundle_fqids_url to specify input analysis bundles; bundle_fqids expects a list of fully-qualified IDs (bundle_uuid.bundle_version); bundle_fqids_url expects a URL that serves a Data Browser download manifest TSV file. Use the format field to specify the desired file format of the output expression matrix. Supported format values are 'loom', 'csv' and 'mtx'.  (optional)
  # @return [V0MatrixPostResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

