# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V0MatrixRequestStatus")

model.instance <- V0MatrixRequestStatus$new()

