# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V0MatrixErrorResponse")

model.instance <- V0MatrixErrorResponse$new()

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

