# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V0MatrixGetResponse")

model.instance <- V0MatrixGetResponse$new()

test_that("request_id", {
  # tests for the property `request_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`request_id`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (V0MatrixRequestStatus)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("matrix_location", {
  # tests for the property `matrix_location` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`matrix_location`, "EXPECTED_RESULT")
})

test_that("eta", {
  # tests for the property `eta` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`eta`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

