# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V1CategoricalFieldDetailAllOf")

model.instance <- V1CategoricalFieldDetailAllOf$new()

test_that("cell_counts", {
  # tests for the property `cell_counts` (map(integer))
  # Count of cells associated with each possible value of the field. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`cell_counts`, "EXPECTED_RESULT")
})

