# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V0MatrixErrorResponse
#' @description V0MatrixErrorResponse Class
#' @format An \code{R6Class} generator object
#' @field message   character  [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V0MatrixErrorResponse <- R6::R6Class(
  'V0MatrixErrorResponse',
  public = list(
    `message` = NULL,
    initialize = function(`message`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      V0MatrixErrorResponseObject <- list()
      if (!is.null(self$`message`)) {
        V0MatrixErrorResponseObject[['message']] <-
          self$`message`
      }

      V0MatrixErrorResponseObject
    },
    fromJSON = function(V0MatrixErrorResponseJson) {
      V0MatrixErrorResponseObject <- jsonlite::fromJSON(V0MatrixErrorResponseJson)
      if (!is.null(V0MatrixErrorResponseObject$`message`)) {
        self$`message` <- V0MatrixErrorResponseObject$`message`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V0MatrixErrorResponseJson) {
      V0MatrixErrorResponseObject <- jsonlite::fromJSON(V0MatrixErrorResponseJson)
      self$`message` <- V0MatrixErrorResponseObject$`message`
      self
    }
  )
)
