# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V0MatrixGetResponse
#' @description V0MatrixGetResponse Class
#' @format An \code{R6Class} generator object
#' @field request_id   character  [optional]
#'
#' @field status   \link[hcamatrixapi:v0_MatrixRequestStatus]{  V0MatrixRequestStatus  }  [optional]
#'
#' @field matrix_location   character  [optional]
#'
#' @field eta   character  [optional]
#'
#' @field message   character  [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V0MatrixGetResponse <- R6::R6Class(
  'V0MatrixGetResponse',
  public = list(
    `request_id` = NULL,
    `status` = NULL,
    `matrix_location` = NULL,
    `eta` = NULL,
    `message` = NULL,
    initialize = function(`request_id`=NULL, `status`=NULL, `matrix_location`=NULL, `eta`=NULL, `message`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
      if (!is.null(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!is.null(`matrix_location`)) {
        stopifnot(is.character(`matrix_location`), length(`matrix_location`) == 1)
        self$`matrix_location` <- `matrix_location`
      }
      if (!is.null(`eta`)) {
        stopifnot(is.character(`eta`), length(`eta`) == 1)
        self$`eta` <- `eta`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      V0MatrixGetResponseObject <- list()
      if (!is.null(self$`request_id`)) {
        V0MatrixGetResponseObject[['request_id']] <-
          self$`request_id`
      }
      if (!is.null(self$`status`)) {
        V0MatrixGetResponseObject[['status']] <-
          self$`status`$toJSON()
      }
      if (!is.null(self$`matrix_location`)) {
        V0MatrixGetResponseObject[['matrix_location']] <-
          self$`matrix_location`
      }
      if (!is.null(self$`eta`)) {
        V0MatrixGetResponseObject[['eta']] <-
          self$`eta`
      }
      if (!is.null(self$`message`)) {
        V0MatrixGetResponseObject[['message']] <-
          self$`message`
      }

      V0MatrixGetResponseObject
    },
    fromJSON = function(V0MatrixGetResponseJson) {
      V0MatrixGetResponseObject <- jsonlite::fromJSON(V0MatrixGetResponseJson)
      if (!is.null(V0MatrixGetResponseObject$`request_id`)) {
        self$`request_id` <- V0MatrixGetResponseObject$`request_id`
      }
      if (!is.null(V0MatrixGetResponseObject$`status`)) {
        statusObject <- V0MatrixRequestStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(V0MatrixGetResponseObject$status, auto_unbox = TRUE, digits = NA))
        self$`status` <- statusObject
      }
      if (!is.null(V0MatrixGetResponseObject$`matrix_location`)) {
        self$`matrix_location` <- V0MatrixGetResponseObject$`matrix_location`
      }
      if (!is.null(V0MatrixGetResponseObject$`eta`)) {
        self$`eta` <- V0MatrixGetResponseObject$`eta`
      }
      if (!is.null(V0MatrixGetResponseObject$`message`)) {
        self$`message` <- V0MatrixGetResponseObject$`message`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
        %s
        ',
        jsonlite::toJSON(self$`status`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`matrix_location`)) {
        sprintf(
        '"matrix_location":
          "%s"
                ',
        self$`matrix_location`
        )},
        if (!is.null(self$`eta`)) {
        sprintf(
        '"eta":
          "%s"
                ',
        self$`eta`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V0MatrixGetResponseJson) {
      V0MatrixGetResponseObject <- jsonlite::fromJSON(V0MatrixGetResponseJson)
      self$`request_id` <- V0MatrixGetResponseObject$`request_id`
      self$`status` <- V0MatrixRequestStatus$new()$fromJSON(jsonlite::toJSON(V0MatrixGetResponseObject$status, auto_unbox = TRUE, digits = NA))
      self$`matrix_location` <- V0MatrixGetResponseObject$`matrix_location`
      self$`eta` <- V0MatrixGetResponseObject$`eta`
      self$`message` <- V0MatrixGetResponseObject$`message`
      self
    }
  )
)
