# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V1ComparisonFilterOperator
#' @description V1ComparisonFilterOperator Class
#' @format An \code{R6Class} generator object
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V1ComparisonFilterOperator <- R6::R6Class(
  'V1ComparisonFilterOperator',
  public = list(
    initialize = function(...){
      local.optional.var <- list(...)
    },
    toJSON = function() {
      V1ComparisonFilterOperatorObject <- list()

      V1ComparisonFilterOperatorObject
    },
    fromJSON = function(V1ComparisonFilterOperatorJson) {
      V1ComparisonFilterOperatorObject <- jsonlite::fromJSON(V1ComparisonFilterOperatorJson)
    },
    toJSONString = function() {
      jsoncontent <- c(
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V1ComparisonFilterOperatorJson) {
      V1ComparisonFilterOperatorObject <- jsonlite::fromJSON(V1ComparisonFilterOperatorJson)
      self
    }
  )
)
