# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V1ComparisonFilter
#' @description V1ComparisonFilter Class
#' @format An \code{R6Class} generator object
#' @field op   \link[hcamatrixapi:v1_ComparisonFilterOperator]{  V1ComparisonFilterOperator  }  [optional]
#'
#' @field field   character  [optional]
#'
#' @field value   \link[hcamatrixapi:oneOf&lt;string,number,array&gt;]{  OneOfstringnumberarray  }  [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V1ComparisonFilter <- R6::R6Class(
  'V1ComparisonFilter',
  public = list(
    `op` = NULL,
    `field` = NULL,
    `value` = NULL,
    initialize = function(`op`=NULL, `field`=NULL, `value`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`op`)) {
        stopifnot(R6::is.R6(`op`))
        self$`op` <- `op`
      }
      if (!is.null(`field`)) {
        stopifnot(is.character(`field`), length(`field`) == 1)
        self$`field` <- `field`
      }
      if (!is.null(`value`)) {
        stopifnot(R6::is.R6(`value`))
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      V1ComparisonFilterObject <- list()
      if (!is.null(self$`op`)) {
        V1ComparisonFilterObject[['op']] <-
          self$`op`$toJSON()
      }
      if (!is.null(self$`field`)) {
        V1ComparisonFilterObject[['field']] <-
          self$`field`
      }
      if (!is.null(self$`value`)) {
        V1ComparisonFilterObject[['value']] <-
          self$`value`$toJSON()
      }

      V1ComparisonFilterObject
    },
    fromJSON = function(V1ComparisonFilterJson) {
      V1ComparisonFilterObject <- jsonlite::fromJSON(V1ComparisonFilterJson)
      if (!is.null(V1ComparisonFilterObject$`op`)) {
        opObject <- V1ComparisonFilterOperator$new()
        opObject$fromJSON(jsonlite::toJSON(V1ComparisonFilterObject$op, auto_unbox = TRUE, digits = NA))
        self$`op` <- opObject
      }
      if (!is.null(V1ComparisonFilterObject$`field`)) {
        self$`field` <- V1ComparisonFilterObject$`field`
      }
      if (!is.null(V1ComparisonFilterObject$`value`)) {
        valueObject <- OneOfstringnumberarray$new()
        valueObject$fromJSON(jsonlite::toJSON(V1ComparisonFilterObject$value, auto_unbox = TRUE, digits = NA))
        self$`value` <- valueObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`op`)) {
        sprintf(
        '"op":
        %s
        ',
        jsonlite::toJSON(self$`op`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`field`)) {
        sprintf(
        '"field":
          "%s"
                ',
        self$`field`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
        %s
        ',
        jsonlite::toJSON(self$`value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V1ComparisonFilterJson) {
      V1ComparisonFilterObject <- jsonlite::fromJSON(V1ComparisonFilterJson)
      self$`op` <- V1ComparisonFilterOperator$new()$fromJSON(jsonlite::toJSON(V1ComparisonFilterObject$op, auto_unbox = TRUE, digits = NA))
      self$`field` <- V1ComparisonFilterObject$`field`
      self$`value` <- OneOfstringnumberarray$new()$fromJSON(jsonlite::toJSON(V1ComparisonFilterObject$value, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
