# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V1LogicalFilterOperator
#' @description V1LogicalFilterOperator Class
#' @format An \code{R6Class} generator object
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V1LogicalFilterOperator <- R6::R6Class(
  'V1LogicalFilterOperator',
  public = list(
    initialize = function(, ...){
      local.optional.var <- list(...)
    },
    toJSON = function() {
      V1LogicalFilterOperatorObject <- list()

      V1LogicalFilterOperatorObject
    },
    fromJSON = function(V1LogicalFilterOperatorJson) {
      V1LogicalFilterOperatorObject <- jsonlite::fromJSON(V1LogicalFilterOperatorJson)
    },
    toJSONString = function() {
      jsoncontent <- c(
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V1LogicalFilterOperatorJson) {
      V1LogicalFilterOperatorObject <- jsonlite::fromJSON(V1LogicalFilterOperatorJson)
      self
    }
  )
)
