# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V1LogicalFilter
#' @description V1LogicalFilter Class
#' @format An \code{R6Class} generator object
#' @field op   \link[hcamatrixapi:v1_LogicalFilterOperator]{  V1LogicalFilterOperator  }  [optional]
#'
#' @field value   \link[hcamatrixapi:oneOf&lt;v1_ComparisonFilter,v1_LogicalFilter,array&gt;]{  OneOfv1ComparisonFilterv1LogicalFilterarray  }  [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V1LogicalFilter <- R6::R6Class(
  'V1LogicalFilter',
  public = list(
    `op` = NULL,
    `value` = NULL,
    initialize = function(`op`=NULL, `value`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`op`)) {
        stopifnot(R6::is.R6(`op`))
        self$`op` <- `op`
      }
      if (!is.null(`value`)) {
        stopifnot(R6::is.R6(`value`))
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      V1LogicalFilterObject <- list()
      if (!is.null(self$`op`)) {
        V1LogicalFilterObject[['op']] <-
          self$`op`$toJSON()
      }
      if (!is.null(self$`value`)) {
        V1LogicalFilterObject[['value']] <-
          self$`value`$toJSON()
      }

      V1LogicalFilterObject
    },
    fromJSON = function(V1LogicalFilterJson) {
      V1LogicalFilterObject <- jsonlite::fromJSON(V1LogicalFilterJson)
      if (!is.null(V1LogicalFilterObject$`op`)) {
        opObject <- V1LogicalFilterOperator$new()
        opObject$fromJSON(jsonlite::toJSON(V1LogicalFilterObject$op, auto_unbox = TRUE, digits = NA))
        self$`op` <- opObject
      }
      if (!is.null(V1LogicalFilterObject$`value`)) {
        valueObject <- OneOfv1ComparisonFilterv1LogicalFilterarray$new()
        valueObject$fromJSON(jsonlite::toJSON(V1LogicalFilterObject$value, auto_unbox = TRUE, digits = NA))
        self$`value` <- valueObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`op`)) {
        sprintf(
        '"op":
        %s
        ',
        jsonlite::toJSON(self$`op`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
        %s
        ',
        jsonlite::toJSON(self$`value`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V1LogicalFilterJson) {
      V1LogicalFilterObject <- jsonlite::fromJSON(V1LogicalFilterJson)
      self$`op` <- V1LogicalFilterOperator$new()$fromJSON(jsonlite::toJSON(V1LogicalFilterObject$op, auto_unbox = TRUE, digits = NA))
      self$`value` <- OneOfv1ComparisonFilterv1LogicalFilterarray$new()$fromJSON(jsonlite::toJSON(V1LogicalFilterObject$value, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
