# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V1MatrixGetResponse
#' @description V1MatrixGetResponse Class
#' @format An \code{R6Class} generator object
#' @field request_id   character  
#'
#' @field status   character  
#'
#' @field matrix_url   character  [optional]
#'
#' @field message   character  [optional]
#'
#' @field eta   character  [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V1MatrixGetResponse <- R6::R6Class(
  'V1MatrixGetResponse',
  public = list(
    `request_id` = NULL,
    `status` = NULL,
    `matrix_url` = NULL,
    `message` = NULL,
    `eta` = NULL,
    initialize = function(`request_id`, `status`, `matrix_url`=NULL, `message`=NULL, `eta`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`matrix_url`)) {
        stopifnot(is.character(`matrix_url`), length(`matrix_url`) == 1)
        self$`matrix_url` <- `matrix_url`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`eta`)) {
        stopifnot(is.character(`eta`), length(`eta`) == 1)
        self$`eta` <- `eta`
      }
    },
    toJSON = function() {
      V1MatrixGetResponseObject <- list()
      if (!is.null(self$`request_id`)) {
        V1MatrixGetResponseObject[['request_id']] <-
          self$`request_id`
      }
      if (!is.null(self$`status`)) {
        V1MatrixGetResponseObject[['status']] <-
          self$`status`
      }
      if (!is.null(self$`matrix_url`)) {
        V1MatrixGetResponseObject[['matrix_url']] <-
          self$`matrix_url`
      }
      if (!is.null(self$`message`)) {
        V1MatrixGetResponseObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`eta`)) {
        V1MatrixGetResponseObject[['eta']] <-
          self$`eta`
      }

      V1MatrixGetResponseObject
    },
    fromJSON = function(V1MatrixGetResponseJson) {
      V1MatrixGetResponseObject <- jsonlite::fromJSON(V1MatrixGetResponseJson)
      if (!is.null(V1MatrixGetResponseObject$`request_id`)) {
        self$`request_id` <- V1MatrixGetResponseObject$`request_id`
      }
      if (!is.null(V1MatrixGetResponseObject$`status`)) {
        self$`status` <- V1MatrixGetResponseObject$`status`
      }
      if (!is.null(V1MatrixGetResponseObject$`matrix_url`)) {
        self$`matrix_url` <- V1MatrixGetResponseObject$`matrix_url`
      }
      if (!is.null(V1MatrixGetResponseObject$`message`)) {
        self$`message` <- V1MatrixGetResponseObject$`message`
      }
      if (!is.null(V1MatrixGetResponseObject$`eta`)) {
        self$`eta` <- V1MatrixGetResponseObject$`eta`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`matrix_url`)) {
        sprintf(
        '"matrix_url":
          "%s"
                ',
        self$`matrix_url`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`eta`)) {
        sprintf(
        '"eta":
          "%s"
                ',
        self$`eta`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V1MatrixGetResponseJson) {
      V1MatrixGetResponseObject <- jsonlite::fromJSON(V1MatrixGetResponseJson)
      self$`request_id` <- V1MatrixGetResponseObject$`request_id`
      self$`status` <- V1MatrixGetResponseObject$`status`
      self$`matrix_url` <- V1MatrixGetResponseObject$`matrix_url`
      self$`message` <- V1MatrixGetResponseObject$`message`
      self$`eta` <- V1MatrixGetResponseObject$`eta`
      self
    }
  )
)
