# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V1MatrixPostResponse
#' @description V1MatrixPostResponse Class
#' @format An \code{R6Class} generator object
#' @field request_id   character  [optional]
#'
#' @field non_human_request_ids    named list(character)   [optional]
#'
#' @field status   character  [optional]
#'
#' @field message   character  [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V1MatrixPostResponse <- R6::R6Class(
  'V1MatrixPostResponse',
  public = list(
    `request_id` = NULL,
    `non_human_request_ids` = NULL,
    `status` = NULL,
    `message` = NULL,
    initialize = function(`request_id`=NULL, `non_human_request_ids`=NULL, `status`=NULL, `message`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`request_id`)) {
        stopifnot(is.character(`request_id`), length(`request_id`) == 1)
        self$`request_id` <- `request_id`
      }
      if (!is.null(`non_human_request_ids`)) {
        stopifnot(is.vector(`non_human_request_ids`), length(`non_human_request_ids`) != 0)
        sapply(`non_human_request_ids`, function(x) stopifnot(is.character(x)))
        self$`non_human_request_ids` <- `non_human_request_ids`
      }
      if (!is.null(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      V1MatrixPostResponseObject <- list()
      if (!is.null(self$`request_id`)) {
        V1MatrixPostResponseObject[['request_id']] <-
          self$`request_id`
      }
      if (!is.null(self$`non_human_request_ids`)) {
        V1MatrixPostResponseObject[['non_human_request_ids']] <-
          self$`non_human_request_ids`
      }
      if (!is.null(self$`status`)) {
        V1MatrixPostResponseObject[['status']] <-
          self$`status`
      }
      if (!is.null(self$`message`)) {
        V1MatrixPostResponseObject[['message']] <-
          self$`message`
      }

      V1MatrixPostResponseObject
    },
    fromJSON = function(V1MatrixPostResponseJson) {
      V1MatrixPostResponseObject <- jsonlite::fromJSON(V1MatrixPostResponseJson)
      if (!is.null(V1MatrixPostResponseObject$`request_id`)) {
        self$`request_id` <- V1MatrixPostResponseObject$`request_id`
      }
      if (!is.null(V1MatrixPostResponseObject$`non_human_request_ids`)) {
        self$`non_human_request_ids` <- ApiClient$new()$deserializeObj(V1MatrixPostResponseObject$`non_human_request_ids`, "map(character)", "package:hcamatrixapi")
      }
      if (!is.null(V1MatrixPostResponseObject$`status`)) {
        self$`status` <- V1MatrixPostResponseObject$`status`
      }
      if (!is.null(V1MatrixPostResponseObject$`message`)) {
        self$`message` <- V1MatrixPostResponseObject$`message`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`request_id`)) {
        sprintf(
        '"request_id":
          "%s"
                ',
        self$`request_id`
        )},
        if (!is.null(self$`non_human_request_ids`)) {
        sprintf(
        '"non_human_request_ids":
          "%s"
        ',
        jsonlite::toJSON(lapply(self$`non_human_request_ids`, function(x){ x }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`status`)) {
        sprintf(
        '"status":
          "%s"
                ',
        self$`status`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V1MatrixPostResponseJson) {
      V1MatrixPostResponseObject <- jsonlite::fromJSON(V1MatrixPostResponseJson)
      self$`request_id` <- V1MatrixPostResponseObject$`request_id`
      self$`non_human_request_ids` <- ApiClient$new()$deserializeObj(V1MatrixPostResponseObject$`non_human_request_ids`, "map(character)","package:hcamatrixapi")
      self$`status` <- V1MatrixPostResponseObject$`status`
      self$`message` <- V1MatrixPostResponseObject$`message`
      self
    }
  )
)
