# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V1NumericFieldDetailAllOf
#' @description V1NumericFieldDetailAllOf Class
#' @format An \code{R6Class} generator object
#' @field minimum   numeric  
#'
#' @field maximum   numeric  
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V1NumericFieldDetailAllOf <- R6::R6Class(
  'V1NumericFieldDetailAllOf',
  public = list(
    `minimum` = NULL,
    `maximum` = NULL,
    initialize = function(`minimum`, `maximum`, ...){
      local.optional.var <- list(...)
      if (!missing(`minimum`)) {
        self$`minimum` <- `minimum`
      }
      if (!missing(`maximum`)) {
        self$`maximum` <- `maximum`
      }
    },
    toJSON = function() {
      V1NumericFieldDetailAllOfObject <- list()
      if (!is.null(self$`minimum`)) {
        V1NumericFieldDetailAllOfObject[['minimum']] <-
          self$`minimum`
      }
      if (!is.null(self$`maximum`)) {
        V1NumericFieldDetailAllOfObject[['maximum']] <-
          self$`maximum`
      }

      V1NumericFieldDetailAllOfObject
    },
    fromJSON = function(V1NumericFieldDetailAllOfJson) {
      V1NumericFieldDetailAllOfObject <- jsonlite::fromJSON(V1NumericFieldDetailAllOfJson)
      if (!is.null(V1NumericFieldDetailAllOfObject$`minimum`)) {
        self$`minimum` <- V1NumericFieldDetailAllOfObject$`minimum`
      }
      if (!is.null(V1NumericFieldDetailAllOfObject$`maximum`)) {
        self$`maximum` <- V1NumericFieldDetailAllOfObject$`maximum`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`minimum`)) {
        sprintf(
        '"minimum":
          %d
                ',
        self$`minimum`
        )},
        if (!is.null(self$`maximum`)) {
        sprintf(
        '"maximum":
          %d
                ',
        self$`maximum`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V1NumericFieldDetailAllOfJson) {
      V1NumericFieldDetailAllOfObject <- jsonlite::fromJSON(V1NumericFieldDetailAllOfJson)
      self$`minimum` <- V1NumericFieldDetailAllOfObject$`minimum`
      self$`maximum` <- V1NumericFieldDetailAllOfObject$`maximum`
      self
    }
  )
)
