# HCA Matrix Service
#
# Human Cell Atlas Matrix Service API
#
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title V1NumericFieldDetail
#' @description V1NumericFieldDetail Class
#' @format An \code{R6Class} generator object
#' @field field_name   character  
#'
#' @field field_description   character  
#'
#' @field field_type   character  
#'
#' @field minimum   numeric  
#'
#' @field maximum   numeric  
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
V1NumericFieldDetail <- R6::R6Class(
  'V1NumericFieldDetail',
  public = list(
    `field_name` = NULL,
    `field_description` = NULL,
    `field_type` = NULL,
    `minimum` = NULL,
    `maximum` = NULL,
    initialize = function(`field_name`, `field_description`, `field_type`, `minimum`, `maximum`, ...){
      local.optional.var <- list(...)
      if (!missing(`field_name`)) {
        stopifnot(is.character(`field_name`), length(`field_name`) == 1)
        self$`field_name` <- `field_name`
      }
      if (!missing(`field_description`)) {
        stopifnot(is.character(`field_description`), length(`field_description`) == 1)
        self$`field_description` <- `field_description`
      }
      if (!missing(`field_type`)) {
        stopifnot(is.character(`field_type`), length(`field_type`) == 1)
        self$`field_type` <- `field_type`
      }
      if (!missing(`minimum`)) {
        self$`minimum` <- `minimum`
      }
      if (!missing(`maximum`)) {
        self$`maximum` <- `maximum`
      }
    },
    toJSON = function() {
      V1NumericFieldDetailObject <- list()
      if (!is.null(self$`field_name`)) {
        V1NumericFieldDetailObject[['field_name']] <-
          self$`field_name`
      }
      if (!is.null(self$`field_description`)) {
        V1NumericFieldDetailObject[['field_description']] <-
          self$`field_description`
      }
      if (!is.null(self$`field_type`)) {
        V1NumericFieldDetailObject[['field_type']] <-
          self$`field_type`
      }
      if (!is.null(self$`minimum`)) {
        V1NumericFieldDetailObject[['minimum']] <-
          self$`minimum`
      }
      if (!is.null(self$`maximum`)) {
        V1NumericFieldDetailObject[['maximum']] <-
          self$`maximum`
      }

      V1NumericFieldDetailObject
    },
    fromJSON = function(V1NumericFieldDetailJson) {
      V1NumericFieldDetailObject <- jsonlite::fromJSON(V1NumericFieldDetailJson)
      if (!is.null(V1NumericFieldDetailObject$`field_name`)) {
        self$`field_name` <- V1NumericFieldDetailObject$`field_name`
      }
      if (!is.null(V1NumericFieldDetailObject$`field_description`)) {
        self$`field_description` <- V1NumericFieldDetailObject$`field_description`
      }
      if (!is.null(V1NumericFieldDetailObject$`field_type`)) {
        self$`field_type` <- V1NumericFieldDetailObject$`field_type`
      }
      if (!is.null(V1NumericFieldDetailObject$`minimum`)) {
        self$`minimum` <- V1NumericFieldDetailObject$`minimum`
      }
      if (!is.null(V1NumericFieldDetailObject$`maximum`)) {
        self$`maximum` <- V1NumericFieldDetailObject$`maximum`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`field_name`)) {
        sprintf(
        '"field_name":
          "%s"
                ',
        self$`field_name`
        )},
        if (!is.null(self$`field_description`)) {
        sprintf(
        '"field_description":
          "%s"
                ',
        self$`field_description`
        )},
        if (!is.null(self$`field_type`)) {
        sprintf(
        '"field_type":
          "%s"
                ',
        self$`field_type`
        )},
        if (!is.null(self$`minimum`)) {
        sprintf(
        '"minimum":
          %d
                ',
        self$`minimum`
        )},
        if (!is.null(self$`maximum`)) {
        sprintf(
        '"maximum":
          %d
                ',
        self$`maximum`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(V1NumericFieldDetailJson) {
      V1NumericFieldDetailObject <- jsonlite::fromJSON(V1NumericFieldDetailJson)
      self$`field_name` <- V1NumericFieldDetailObject$`field_name`
      self$`field_description` <- V1NumericFieldDetailObject$`field_description`
      self$`field_type` <- V1NumericFieldDetailObject$`field_type`
      self$`minimum` <- V1NumericFieldDetailObject$`minimum`
      self$`maximum` <- V1NumericFieldDetailObject$`maximum`
      self
    }
  )
)
